<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="example">
  <xacro:include filename="$(find velodyne_description)/urdf/VLP-16.urdf.xacro"/>
  <VLP-16 parent="top_plate_link" name="velodyne" topic="/velodyne_points" hz="10" samples="440">
     <origin xyz="-0.075 0.0 0.08635" rpy="0 0 0" />
  </VLP-16>

  <!-- Macro to add a thermal camera {-->
  <!--<xacro:macro name="thermal_camera_macro" params="namespace parent_frame_name camera_frame_name sensor_base_frame_name camera_topic_name camera_suffix parent_link frame_rate hfov x y z roll pitch yaw image_width image_height color">
    <link name="${robot_namespace}/${camera_frame_name}/thermal_camera_link">
      <visual>
        <origin xyz="0 0 0" rpy="1.57079632679 0 0" />
        <geometry>
          <mesh filename="$(find mbzirc_husky)/simulation/bluefox.dae" scale="1 1 1" />
        </geometry>
      </visual>
    </link>

    <joint name="/husky/thermal_camera_joint" type="fixed">
      <origin xyz="0 0 0.5" rpy="0 0 0"/>
      <parent link="top_plate_link" />
      <child link="/husky/thermal_camera_link" />
    </joint>

    <gazebo reference="/husky/thermal_camera_link">
      <sensor type="camera" name="mrs_thermal_camera_sensor">
        <update_rate>10</update_rate>
        <camera>
          <horizontal_fov>3</horizontal_fov>
          <image>
            <format>R8G8B8</format>
            <width>30</width>
            <height>30</height>
          </image>
          <clip>
            <near>0.1</near>
            <far>300</far>
          </clip>
        </camera>
        <plugin name="thermal_camera_controller" filename="libmrs_gazebo_ros_thermal_camera.so">
          <alwaysOn>true</alwaysOn>
          <cameraName>thermal</cameraName>
          <updateRate>10</updateRate>
          <imageTopicName>/husky/rgb_image</imageTopicName>
          <cameraInfoTopicName>/husky/camera_info</cameraInfoTopicName>
          <rawTemperatureTopicName>/husky/raw_temp_array</rawTemperatureTopicName>
          <surroundingTemperature>20</surroundingTemperature>
          <maximalTemperature>150</maximalTemperature>
          <minimalTemperatureGreenColor>0.2</minimalTemperatureGreenColor>
          <noiseStdDev>4.0</noiseStdDev>
          <noiseStdDevMaxTemp>20.0</noiseStdDevMaxTemp>
          <frameName>therm</frameName>
          <parentFrameName>top_plate_link</parentFrameName>
          <sensorBaseFrameName>therm</sensorBaseFrameName>
          <x>0</x>
          <y>0</y>
          <z>0.5</z>
          <roll>0</roll>
          <pitch>0</pitch>
          <yaw>0</yaw>
        </plugin>
      </sensor>
    </gazebo>    
    <gazebo reference="/husky/thermal_camera_link">
      <material>Gazebo/blue</material>
    </gazebo>
  </xacro:macro>-->

  <!--ORIGINAL-->
  <!-- Macro to add a thermal camera {-->
  <xacro:macro name="thermal_camera_macro" params="namespace robot_namespace parent_frame_name camera_frame_name sensor_base_frame_name camera_topic_name camera_suffix parent_link frame_rate hfov x y z roll pitch yaw image_width image_height color">
    <link name="${robot_namespace}/${camera_frame_name}/thermal_camera_link">
      <visual>
        <origin xyz="0 0 0" rpy="1.57079632679 0 0" />
        <geometry>
          <mesh filename="$(find mbzirc_husky)/models/bluefox.dae" scale="1 1 1" />
        </geometry>
      </visual>
    </link>

    <joint name="${robot_namespace}/${camera_frame_name}/thermal_camera_joint" type="fixed">
      <origin xyz="${x} ${y} ${z}" rpy="${roll} ${pitch} ${yaw}"/>
      <parent link="${parent_link}" />
      <child link="${namespace}/${camera_frame_name}/thermal_camera_link" />
    </joint>

    <gazebo reference="${robot_namespace}/${camera_frame_name}/thermal_camera_link">
      <sensor type="camera" name="mrs_thermal_camera_sensor">
        <update_rate>${frame_rate}</update_rate>
        <camera>
          <horizontal_fov>${hfov}</horizontal_fov>
          <image>
            <format>R8G8B8</format>
            <width>${2 * image_width}</width>
            <height>${2 * image_height}</height>
          </image>
          <clip>
            <near>0.1</near>
            <far>300</far>
          </clip>
        </camera>
        <plugin name="thermal_camera_controller" filename="libmrs_gazebo_ros_thermal_camera.so">
          <alwaysOn>true</alwaysOn>
          <cameraName>${camera_suffix}</cameraName>
          <updateRate>${frame_rate}</updateRate>
          <imageTopicName>${camera_topic_name}/rgb_image</imageTopicName>
          <cameraInfoTopicName>${camera_topic_name}/camera_info</cameraInfoTopicName>
          <rawTemperatureTopicName>${camera_topic_name}/raw_temp_array</rawTemperatureTopicName>
          <surroundingTemperature>20</surroundingTemperature>
          <maximalTemperature>150</maximalTemperature>
          <minimalTemperatureGreenColor>0.2</minimalTemperatureGreenColor>
          <noiseStdDev>4.0</noiseStdDev>
          <noiseStdDevMaxTemp>20.0</noiseStdDevMaxTemp>
          <frameName>${camera_frame_name}</frameName>
          <parentFrameName>${parent_frame_name}</parentFrameName>
          <sensorBaseFrameName>${sensor_base_frame_name}</sensorBaseFrameName>
          <x>${x}</x>
          <y>${y}</y>
          <z>${z}</z>
          <roll>${roll}</roll>
          <pitch>${pitch}</pitch>
          <yaw>${yaw}</yaw>
        </plugin>
      </sensor>
    </gazebo>    
    :<gazebo reference="${robot_namespace}/thermal_camera_link">
      <material>Gazebo/${color}</material>
    </gazebo>
  </xacro:macro>

  <!-- Thermal camera {-->
  <xacro:thermal_camera_macro
    namespace="/husky"
    robot_namespace="/husky"
    parent_frame_name="top_plate_link"
    sensor_base_frame_name="themal_base"
    camera_frame_name="thermal_camera_frame_husky"
    camera_topic_name="/husky/thermal/"
    parent_link="base_link"
    camera_suffix="thermal_top"
    frame_rate="14.0"
    hfov="0.575959"
    image_width="32"
    image_height="32"
    x="0.4"
    y="0"
    z="0.4"
    roll="0"
    pitch="0.0"
    yaw="0"
    color="Yellow">
  </xacro:thermal_camera_macro>


</robot>
