name: kinova
root: ./
startup_window: kortex_control_manager 
pre_window: export UAV_NAME=uav1; export RUN_TYPE=simulation; export UAV_TYPE=t650; export WORLD_NAME=simulation
windows:
  - roscore:
      layout: even-vertical
      panes:
        - roscore
  - arm_drivers:
      layout: even-vertical
      panes:
        - sleep 2; roslaunch kortex_driver kortex_driver.launch start_moveit:=true start_rviz:=false
        - sleep 3; roslaunch iiwa_moveit_pouring moveit_action.launch
  - kortex_control_manager:
      layout: even-vertical
      panes:
        - sleep 4; roslaunch kortex_control_manager control_manager.launch
        - sleep 6; rostopic echo /kinova/arm_manager/status
        - 'history -s rosservice call /kinova/arm_manager/'
